apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snake-game-web.fullname" . }}
  labels:
    {{- include "snake-game-web.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "snake-game-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "snake-game-web.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: snake-game-web
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000