name: Docker Image CI

on:
  push:
    tags: 
      - 'v*'
  workflow_dispatch:
env:
  IMAGE_NAME: zzq-cr01-ap-southeast-1.cr.bytepluses.com/cl-test-ns/snake-game-web


jobs:
  build docker image:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag $IMAGE_NAME:${{ github.ref_name }} .
    - name: Docker login
      run: docker login --username=${{ secrets.CR_USERNAME }} --password=${{ secrets.CR_PASSWORD }} zzq-cr01-ap-southeast-1.cr.bytepluses.com
    - name: Push the Docker image
      run: docker push $IMAGE_NAME:${{ github.ref_name }}
  deploy to vke:
    runs-on: self-hosted
    needs: build docker image