name: Build and Deploy

on:
  push:
    tags: 
      - 'v*'
  workflow_dispatch:
env:
  IMAGE_NAME: zzq-cr01-ap-southeast-1.cr.bytepluses.com/cl-test-ns/snake-game-web

jobs:
  build-docker-image:
    runs-on: [self-hosted, gh-runner2]
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag $IMAGE_NAME:${{ github.ref_name }} .
    - name: Docker login
      run: docker login --username=${{ secrets.CR_USERNAME }} --password=${{ secrets.CR_PASSWORD }} zzq-cr01-ap-southeast-1.cr.bytepluses.com
    - name: Push the Docker image
      run: docker push $IMAGE_NAME:${{ github.ref_name }}

  deploy-to-vke:
    runs-on: [self-hosted, gh-runner2]
    needs: build-docker-image
    steps:
    - uses: yokawasa/action-setup-kube-tools@v0.11.2
      with:
        setup-tools: |
          helm
          kubectl
        kubectl: '1.32.3'
        helm: '3.17.3'
    - name: Setup ~/.kube/config
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
    - name: Deploy Helm Chart
      run: |
        helm install sgw-release ./helm-chart --set image.tag=${{ github.ref_name }}
